### ISSUE TITLE
verification emails coming  from non-existent domain

### ISSUE THREAD

**Issue by kesiganes** [requestly/requestly#101]
NOQUEUE: reject: RCPT from mail-vk1-f198.google.com[209.85.221.198]: 450 4.1.8 <noreply@fbmails.requestly.io>: Sender address rejected: Domain not found

**Comment by requestly-team** [comment]
Thank you @kesiganes for logging this issue. We'll look into it.

**Comment by requestly-team** [comment]
Hey @kesiganes We send emails via Firebase. Is the verification email being rejected by your email provider?

**Comment by kesiganes** [comment]
> Hey @kesiganes We send emails via Firebase. Is the verification email being rejected by your email provider?

yes. and i tend to agree with them. seems totally logical to me not to accept emails from nonexistant domains. 
from postfix doc:
reject_unknown_sender_domain
  Reject the request when Postfix is not final destination for the sender address, and the MAIL FROM domain has 1) no DNS 
  MX and no DNS A record, or 2) a malformed MX record such as a record with a zero-length MX hostname

**Comment by Bagpuss** [comment]
This is still a problem. I have the message "Please verify your email to continue using Requestly, 3 days left" but my server is rejecting your emails because they use the address [noreply@fbmails.requestly.io](mailto:noreply@fbmails.requestly.io) which has a domain that does not resolve. I'm not going to make changes to my mail server to accept your broken emails. It's also not possible for me to change my email address to something else in the account settings, presumably that is only possible after verification.

**Comment by sagarsoni7** [comment]
Hi @Bagpuss! Thanks for bringing this issue into our attention. I'll try to fix the email asap.
For now, can you please send me "hi" at sagar@requestly.io so that I could manually mark your email as verified?

**Comment by sagarsoni7** [comment]
Sending email changed to an existent domain
