### ISSUE TITLE
Redirecting file too slow

### ISSUE THREAD

**Issue by deleteduser2** [requestly/requestly#121]
Async script call in the start of the website fucks everything up just because the proxy file gets loaded TOO LATE for some reason. Global value is set after the async script is being evaluated and everything is fucked because the global is supposed to be already set by the proxy.

Fix this beta ordering / delay / whatever and bring back local file redirection, your cloud storage is 💩.

**Comment by requestly-team** [comment]
Hey, Thanks for logging this issue. Are you talking in the context of desktop app?
Can you please help with more details like the rule which you have created and the site on which you are doing the test?

We will be able to investigate this better then!

**Comment by joeyjiron06** [comment]
hi @requestly-team, I would like to resurrect this issue. I love this product for it's ease of use, so thanks for all the amazing/hard work you've put into this product. 

I am redirecting a request to send a local file and the response takes like 10 seconds for your server to respond (see attachment). I tested this with fiddler and it was nearly instantaneous. I'm currently using a free trial version of "professional", so not sure if that has anything to do with it, but curious if this is something you can fix?

![Image 2023-12-13 at 5 07 34 PM](https://github.com/requestly/requestly/assets/4155428/fd26816f-eaaf-4e02-8bc3-4ac8e18ce850)

![Starfield_ Available Now on Console, PC, and Game Pass _ Xbox and 8 more pa  2023-12-13 at 5 10 39 PM](https://github.com/requestly/requestly/assets/4155428/86929ca3-4a25-41fa-9f90-5aa2d0a618ba)

**Comment by nsrCodes** [comment]
@joeyjiron06 thanks for pointing this out, we will look into this on priority, can you please share a few details to help us debug this faster:
- which operating system are you on?
- what version of the app are you using?
- what is the size of the file that is being served?

**Comment by nsrCodes** [comment]
Hey @joeyjiron06 
I see that you are using the modify response rule for redirecting to a local file. You can achieve the same thing using the redirect rule (Select the `Local File` option).

The difference between the two is that: 
- in modify response rule, the app reads the contents of the file and then overrides the response with the new contents. So basically the original request is first made. This is useful when you want to preserve the response headers and status code and only override the response body
- in the redirect rule the the request flow is stopped and the app directly serves the contents of the file with a 200 status code. 

Since in the first case the original request is still made, which is then followed by a file read from disk, the time time exceeds significantly compared to when you just use the redirect rule.
So let me know if redirect rule is fast enough for your use case

**Comment by joeyjiron06** [comment]
Hi @nsrCodes,

sorry I missed your previous message. Yes I can certainly try the local file redirect and see what happens, thanks for the direction here. I’ll let you know soon!

**Comment by nsrCodes** [comment]
@joeyjiron06 can you please confirm if the local file redirect solved the issue that you were facing?

**Comment by joeyjiron06** [comment]
Hi @nsrCodes, yes that solved my issue. Thanks!

**Comment by nsrCodes** [comment]
Awesome!
