### ISSUE TITLE
Response Headers are not being passed with 302 Redirect

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#166]
When we open https://work.8x8.com there's a series of 3xx redirects, but we get an empty page because the response headers are missing.

**Comment by sahil865gupta** [comment]
Response Headers was not getting passed from Requestly to Browser in some cases. This was introduced in v0.0.21-beta when we released `Response Status Code Modification` Feature. 

This is fixed in v0.0.22-beta
https://github.com/requestly/requestly/releases/download/v0.0.22-beta/Requestly-0.0.22-beta.dmg

**Comment by sachinjain024** [comment]
@sahil865gupta I guess this bug has been fixed and app has been released too?

**Comment by sahil865gupta** [comment]
> @sahil865gupta I guess this bug has been fixed and app has been released too?

Yep this is released already.
