### ISSUE TITLE
bug: HTML custom elements fails to inject in sites with strict CSP

### ISSUE THREAD

**Issue by zidad** [requestly/requestly#1830]
I'm getting a lot of errors in the console on sites with CSP enabled, seems like requestly is trying to do a lot more than just the rules I specified (modifying headers).

![Screenshot 2024-06-18 at 12 33 38](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/524b1eb6-9196-47e7-b1aa-813d3171b299/10fe9aa4-1832-4cde-9c3e-ace55648ad72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi81MjRiMWViNi05MTk2LTQ3ZTctYjFhYS04MTNkMzE3MWIyOTkvMTBmZTlhYTQtMTgzMi00Y2RlLTljM2UtYWNlNTU2NDhhZDcyIiwiaWF0IjoxNzE4OTUyMDk4LCJleHAiOjMzMjg5NTEyMDk4fQ.taeh83a0NYFCteEcOzI2FKJYiDD9aHfe8pU4vfS9fGI "=2276x")

**Comment by wrongsahil** [comment]
Hey @zidad . To make it easy to monitor whether the rules are applied or not on a page, we inject a custom HTML element. These errors are mostly due to that only but they are completely harmless. You can learn more about the feature [here](https://youtu.be/2Crb4qXw8FA)

You can disable this feature by going to https://app.requestly.io/settings/global-settings . That should get rid of these issues.

**Comment by zidad** [comment]
Great, that worked, thanks! They are harmless but when you're building/debugging sites I don't want to see any errors in my console... Maybe it's possible for requestly to check for CSP policies before trying to inject the elements?

**Comment by wrongsahil** [comment]
Makes sense. These unwanted errors can cause developers to look in the wrong direction. 

We already handle CSP issues in our Response Rule. This can also be handled similarly. Adding this to our triage for now
