### ISSUE TITLE
Stop spamming the console

### ISSUE THREAD

**Issue by Brontojoris** [requestly/requestly#207]
Please stop spamming the console with requestly promotions

![requestly-spam](https://user-images.githubusercontent.com/572375/170898893-166c78a2-c38a-42a4-a770-6a6a78334f7a.png)

These notifications are ugly, visually distracting, and repetitive ... repetitive because they are shown multiple times per page load (taking up more lines in the console than necessary), but also, once I've learned about this feature, I don't need to be reminded about it every time I open the console.

**Comment by lazyvab** [comment]
@Brontojoris Thanks for reporting the issue. 

This message is to notify users that Requestly changed the default behaviour of website by applying some rules. If users wish, they can see each and every modification applied by turning on the setting.

We ensure that the message is printed in console only once per page load, when at least one rule is applied.

But since you are seeing repetitive messages on each page load, it can be one of the two reasons:
1. "Preserve logs" is enabled in console because of which earlier messages are not cleared.
2. Your webpage has a lot of iframes and each iframe has its own logging.

We will soon investigate and fix the experience, so it does not appear as noise.

**Comment by sachinjain024** [comment]
@Brontojoris This has been fixed and rolled out in v22.6.1. This is available in the latest builds on Chrome & Edge. Can you please try this out at your end and let me know if things look good at your end.

**Comment by Brontojoris** [comment]
Thanks @sachinjain024 and @lazyvab. Looks much better.
