### ISSUE TITLE
How to remove delay cap

### ISSUE THREAD

**Issue by greatvovan** [requestly/requestly#236]
I am a new user. For some reason I see this message:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4903007/203863250-155f092f-c6c9-41df-aea1-a9106dcde8b5.png">

How to kindly opt out of this cap?
I need to test a scenario where the applications performs API requests in background, which is supposed to have not interference with any flow. But 5 seconds is just not enough for me to check those flows.

Additionally, I do not see any usefulness in this cap. The explained reason "to avoid browsing performance degradation" does not make any sense as the purpose of the delay is exactly opposite: introduce the performance degradation and see how the application behaves UX-wise. Delay rules are created by people who know what they are doing and why they are doing it. If delay rules do not work as expected, users will make them more focused or disable them.

See also: #127.

**Comment by wrongsahil** [comment]
Hey @greatvovan 
Due to technical constraints, extension have a cap of 5s for delay rule. 
But for now, you can try our [desktop app](https://requestly.io/desktop/). It has a limit of 10s but we will remove this also in next release.

Here's a quick demo of Desktop App
https://www.youtube.com/watch?v=xUdwViRtiY0

**Comment by sachinjain024** [comment]
@lazyvab Can you please take this forward? I guess moving the delay logic from the extension background to the page script should solve this. And the same logic will also work with MV3. 

@greatvovan Are you still impacted by the lower limit in Delay Request Rule?

**Comment by Gesh4o** [comment]
Hello team, first of all - thank you for developing this extension! 

It really helps me a lot when I want to mock request for feature development and re-produce special case scenarios for bug hunting.

Now, I do not know why this limitation exists but I can tell you I wish it was never there. Recently our team started looking into the resiliency of our web app with the intent to allow some critical flows (like login) to continue even if the back-end system is suboptimal. As part of this effort we started testing for responses that timeout after 60 seconds. 

I use the extension almost anytime when I need to intercept something but because of this limitation I have to use other extensions like "ModResponse" (or any other that works).

I also used the desktop app and there was no difference.

**Comment by sachinjain024** [comment]
Thanks @Gesh4o for the feedback! We will take this on priority now and solve it in our next week sprint.

I think instead of capping the limit, we can let the user choose this value and maybe have a large cap like 100s but warn the user that having a large cap may degrade the browsing experience.

cc @ashishsangle707 @lazyvab @wrongsahil

**Comment by wrongsahil** [comment]
@greatvovan @Gesh4o There's no cap on desktop app now. Please try it again if you still need it and let me know how it goes.

Closing this issue. Feel free to reopen incase you are still facing it

**Comment by greatvovan** [comment]
@sachinjain024, sorry for late response. Yes, I can confirm that I am able to set a higher delay using the desktop app.
Thank you.
