### ISSUE TITLE
Pinned rules of a unpinned group when activated from popup wont work.

### ISSUE THREAD

**Issue by rohanmathur91** [requestly/requestly#251]
## Expected Behavior
If a rule is pinned and shown in a popup, on activating it should get applied.

## Current Behavior
Pinned rules of an unpinned group won't work since the group is not active, this is expected, but in the popup, those rules whose groups are not pinned are also shown, which gives the impression that the rules are not working when active.

## Possible Solution 

We should disable the status button for rules shown in the popup whose groups are not pinned and show a tooltip or message indicating that the user needs to activate the group to make the rules work.

**Comment by sachinjain024** [comment]
To simplify the user experience, shouldn't we remove the pinning feature completely and Instead show all the rules in the popup? 

@rohanmathur91 I know some users who have like 100s of rules. Will our popup be able to handle 100 rules in the popup? I mean will the Popup UI break in terms of User Experience or Performance wise.

If not, probably a good option should be to just get rid of manual pinning and show all the rules in the popup for quick access. Thoughts?

**Comment by coreyb-cbs** [comment]
@sachinjain024 I personally would not want all my rules in the popup container by default. I have many rules so it would be too busy to have them all present in that container even if it was nested in an accordion. I much prefer having the ability to only pin my most-often used rules. Perhaps offering the user the ability to show all rules in the popup via a setting?

Some thoughts for my personal usage in relation to the original proposal:
1. I think it would be a good idea to disable the status of a pinned rule and provide a tooltip upon hover to indicate why it's disabled if it's in a group that is disabled (something like "This rule's group is currently deactivated. You must activate the group that this rule belongs to in order to activate this rule").
2. I keep all my rule groups status as active. I have no need to disable an entire group of rules. I could see how someone might use that feature to quickly toggle on/off a set of rules, but I have my rules set up in a way that they serve distinct purposes and I have no need to have multiple rules enabled at the same time. My groups simply serve as a means to organize my rules (ex: routing our core platform js file, routing to diff envs for our api, query params for our privacy cmp, etc).
3. If a user wanted all their rules present in the popup, couldn't they simply add them to a group and then pin the group?

**Comment by sachinjain024** [comment]
Thanks, @coreyb-cbs for your input. It really helps in forming an approach. I also want to make pinning a default choice for the new users to make it easier to jump to the rules and modify them.

- Make it a default choice that after 1st Jan 2023 (Tentatively) all new rules will be auto-pinned to popup
- Provide a flag under /settings to turn this off
- Show an alert in the UI to existing users to update this setting

So for you (& other existing users who want to pin rules themselves), It will just be a quick toggle under /settings route. For others, default wins and their new rules/groups will be auto-pinned to popup.

**Comment by lazyvab** [comment]
Thanks @coreyb-cbs @mallowigi for your suggestions.

I think @sachinjain024's intent by showing all rules is to educate users about the pinning feature, so they can easily access rules from page's context itself.

My 2 cents:
- Instead of showing all rules in the popup, we can show another list of `Recent rules` below `Pinned rules`. In `Recent rules`, we can list rules which were recently created/modified by the user. User will have an option to pin those rules as well.
- In `Pinned rules` list, we can provide an option to add more rules to pinned using a cascading menu (tree-like dropdown) of group and rules.

And for the original problem, IMHO, we should disable status toggle button for rules which belong to a disabled group. Next to it, there should be a yellow warning icon, clicking on which we show a confirmation popover like this:

<img width="291" alt="Screenshot 2022-12-16 at 5 26 24 PM" src="https://user-images.githubusercontent.com/6367566/208093182-1952c600-cb57-4a88-968f-ca260f8ee32a.png">

**Comment by LeaVerou** [comment]
> @coreyb-cbs @mallowigi @LeaVerou Requesting your thoughts on showing all the rules in Popup by default?

Having 100s of rules there would not be helpful. However, having to pin a rule to make it visible there was definitely confusing for me.

How about having a number of rules that show up in the popup (e.g. 10), that are selected as:

- Pinned rules are first
- Most recently toggled rules come after, if there are more slots left after pinned rules are displayed
- If there are still slots left, just display rules in order of creation.

**Comment by sachinjain024** [comment]
Thanks, @LeaVerou a lot for your thoughts!  You're right having lots of rules will pollute the popup experience. We are going ahead with the following then
- Pinned rules
- Recently Modified rules (that'd contain both created/updated rules)

**Comment by coreyb-cbs** [comment]
@sachinjain024 And I think it would be important to visually separate those two categories of rules - horizontal bar, maybe some brief heading ("pinned" and "recently modified").

**Comment by lazyvab** [comment]
@coreyb-cbs @LeaVerou @mallowigi - We recently pushed a major change in extension version `23.1.14`. ([How to update manually?](https://medium.com/requestly/how-to-update-chrome-and-firefox-extensions-manually-29de9798f646))

We now have 3 tabs in the extension popup - `Pinned rules`, `Recently used` and `Executed rules`.
So, `Recently used` which will list the 5 most recently created or modified rules.
`Executed rules` will list all rules that executed in current page.

All rules in these tabs are going to have a pin action.

The other task to avoid status changes in a rule of a disabled group is expected to be shipped in our next release.
