### ISSUE TITLE
bug: Modifying HTTP Status Code works in desktop app but not in browser extension

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [requestly/requestly#310]
### Describe your issue?

Edge Extension doesn't capture the request.
Same rule works using Desktop-App.

### Repro steps

1. Assume we a working have endpoint `GET http://localhost:8000/public-api/templates` which responses 200 OK and a non-empty object in body.
2. We want to change response to 500 error and an empty object in body.
3. We create a "Modify response" rule
* `URL` > `CONTAINS` > `public-api/templates`
* `Response Status Code`: `500`
* `Response Body`: `{}`

# Using Desktop-App
1. Open "Microsoft Edge" from "Connected Apps"
2. Open a new tab and open endpoint `http://localhost:8000/public-api/templates`
3. Response is replaced with the rule we defined

![image](https://user-images.githubusercontent.com/24372782/220597366-d6cf792f-d439-4d03-b72a-f21f9df89316.png)

# Using Edge Extension
1. Do the same as we did in Desktop-App
2. Response is not captured by Requestly at all.

![image](https://user-images.githubusercontent.com/24372782/220597914-92297992-a47e-4815-9204-01e77d3c285f.png)

### What Requestly tool were you using?

- [X] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 10

### Requestly Version

1.4.23

**Comment by wrongsahil** [comment]
Hey @xuan-nguyen-swe . Response Rule in desktop app works for only XHR/Fetch Requests. Also the response modified isn't visible in the devtools panel due to technical limitations. Your isn't working because it isn't a fetch request. 
```
fetch("http://example.com")
  .then((response) => {console.log("Status Code: " +response.status); return response.text()})
  .then((data) => console.log(data));
```
Use this to test whether your Response rule is working in browser extension or not.
Here's the docs for the same https://docs.requestly.io/browser-extension/chrome/http-modifications/response-rule

We are currently working on improving the communication of limitations in extension #342 #340
