### ISSUE TITLE
bug: troubleshoot button leads to a 404

### ISSUE THREAD

**Issue by GauthierPLM** [requestly/requestly#499]
### Describe your issue?

The URL opened by the troubleshoot button in the _Steps to setup System Wide Proxy_ modal leads to a 404 on https://docs.requestly.io/desktop-app/troubleshooting/osx-troubleshooting

### Repro steps

1. Open Requestly desktop and go to Connected Apps tab.
2. Click on « Open » under Everywhere.
3. Let the setup happen.
4. Click on troubleshoot button.
5. Page https://docs.requestly.io/desktop-app/troubleshooting/osx-troubleshooting is opened in browser, resulting in a 404.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11

### Requestly Version

Latest

### Error screenshot

![image](https://user-images.githubusercontent.com/2579741/230729458-7338c56b-fa18-44d3-a9ba-ca7fca0d407d.png)

**Comment by ashishsangle707** [comment]
Hello @GauthierPLM ,

This is Ashish here from the Requestly Product team.

Thank you for bringing this issue to our attention. We apologize for the inconvenience caused by the broken URL.
Please use the following this link to access the correct troubleshooting guides: [https://docs.requestly.io/desktop-app/mac/category/troubleshooting]

We will update the broken URL in the desktop app on priority.

**Comment by wrongsahil** [comment]
Thanks for reporting this @GauthierPLM . We've fixed the issue :D
