### ISSUE TITLE
Make operation filter optional for Modify API Response for GraphQL using Dynamic (JavaScript) option

### ISSUE THREAD

**Issue by caseygum** [requestly/requestly#726]
Presently, only a single Modify API Response GraphQL rule can be applied at any one time.  Sometimes, you will have multiple operations on a single page that request the same data (by different components) and the indeterminate order in which the results come back cause inconsistent effects as entities in the responses get cached.  For instance, you may have multiple operations that ask for the current user permissions.  If you mock the result in one operation, you might have weird behavior because another operation asks for the same data (which you can't change because you can only override one operation at a time).

With a dynamic response, you can recursively walk through the response looking for a specific type (like user permissions) and overwrite the object to test the effects of changing permissions.  If all operations could be processed by a single dynamic rule, you could fix this problem.  For instance:

```
function modifyResponse(args) {
  const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
  // Change response below depending upon request attributes received in args

  var containsPermissions = ...
  var overwritePermissions = ...

  if (containsPermissions(responseJSON)) {
    overwritePermissions(responseJSON);
    return responseJSON;
  }   

  return response;
}
```

So, the request is to make the operation filter optional if the Dynamic response body option is selected.

**Comment by lazyvab** [comment]
@caseygum Thanks for sharing a valid use-case where operation filter should not be mandatory.

Meanwhile we fix it, there is a workaround to unblock you:

You may select `REST API` as resource type instead of `GraphQL`. Currently, the only difference in the way we handle the two is the operation name filter. In `REST` API option, there is no operation name filter applied and your rule will apply to all the GraphQL requests that satisfy the URL source condition in the rule.

<img width="787" alt="image" src="https://github.com/requestly/requestly/assets/6367566/bb03b32b-d142-4dd8-8ac9-330da0467877">

**Comment by lazyvab** [comment]
@caseygum As requested by you, we have made the GraphQL operation filter as optional. 

This will help to save the rule in cases where:
- The request does not contain `operationName` in payload. 
- Operation name is present in request path or query parameter in URL.
- User is using programmatic (JS) mode to filter the request.

Closing the issue. Please feel free to reopen if it does not meet your expectation.
